AgenceEvenementielle/AgenceEvenementielle/Models/ErrorViewModel.cs
namespace AgenceEvenementielle.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgenceEvenementielle/AgenceEvenementielle/Models/Evenement.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AgenceEvenementielle.Models
{
    public class Evenement
    {
       public int Id { get; set; }
        public string Nom {  get; set; }
        public string Lieu { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public string Horraire { get; set; }

        public List<Participant> Participants { get; set; } = new List<Participant>();
        


    }
}

AgenceEvenementielle/AgenceEvenementielle/Models/Participant.cs
namespace AgenceEvenementielle.Models
{
    public class Participant
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }

        public List<Evenement> Evenements { get; set; } = new List<Evenement>();

    }
}

AgenceEvenementielle/AgenceEvenementielle/Models/Statistique.cs
using MongoDB.Bson.Serialization.Attributes;

namespace AgenceEvenementielle.Models
{
    public class Statistique
    {
        [BsonId]
        [BsonRepresentation(MongoDB.Bson.BsonType.ObjectId)]
        public int Id { get; set; }

        [BsonElement("periode")]
        public string Periode { get; set; }

        [BsonElement("inscription")] 
        public string NbInscription { get; set; }

    }
}

AgenceEvenementielle/AgenceEvenementielle/Controllers/EvenementController.cs
using AgenceEvenementielle.Data;
using AgenceEvenementielle.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgenceEvenementielle.Controllers
{
    public class EvenementController : Controller
    {
        private readonly EvenementContext _context;

        public EvenementController(EvenementContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Evenement> evenements = _context.Evenements.OrderBy(evenement => evenement.Nom).ToList();
            return View(evenements);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Evenement evenement)
        {
            _context.Evenements.Add(evenement);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(string id)
        {
            Evenement evenement = _context.Evenements.FirstOrDefault(evenement => evenement.Nom.Equals(id));
            if (evenement == null)
            
                return NotFound();
            
            return View(evenement);
            
        }

        [HttpPost]
        public IActionResult Edit(Evenement evenement)
        { 
            Evenement evenementExistant = _context.Evenements.FirstOrDefault(evenement => evenement.Nom.Equals(evenement.Nom));
            if (evenementExistant == null)
            {
                ViewBag.Erreur = "Cet événement n'existe pas";
                return View(evenement);
            }
            evenementExistant.Nom = evenement.Nom;
            evenementExistant.Lieu = evenement.Lieu;
            evenementExistant.Horraire = evenement.Horraire;
            evenementExistant.Date = evenement.Date;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(string id)
        {
            Evenement evenement = _context.Evenements.FirstOrDefault(evenement => evenement.Nom.Equals(id));
            if (evenement == null)

                return NotFound();

            return View(evenement);
        }

        [HttpPost]
        public IActionResult Delete(Evenement evenement)
        {
            Evenement evenementASuppr = _context.Evenements.FirstOrDefault(evenement => evenement.Nom.Equals(evenement.Nom));
            if (evenementASuppr == null)
            {
                
                return View(evenement);
            }
            _context.Evenements.Remove(evenementASuppr);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Statistique()
        {
            return View();

        }

        public IActionResult Participant()
        {
            var participants = new Participant
            {
                Id = 1,
                Nom = "Martin",
                Prenom = "Jean-Pierre",

            };
            List<Participant> listeParticipants = _context.Participants.OrderBy(participant => participant.Nom).ToList();
            return View(listeParticipants);

        }

        public IActionResult CreateParticipant()
        {
            return View();
        }

    }
}

AgenceEvenementielle/AgenceEvenementielle/Controllers/HomeController.cs
using System.Diagnostics;
using AgenceEvenementielle.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgenceEvenementielle.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Create.cshtml
@model AgenceEvenementielle.Models.Evenement

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Evenement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lieu" class="control-label"></label>
                <input asp-for="Lieu" class="form-control" />
                <span asp-validation-for="Lieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horraire" class="control-label"></label>
                <input asp-for="Horraire" class="form-control" />
                <span asp-validation-for="Horraire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner à la page d'acceuil</a>
</div>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/CreateParticipant.cshtml
@model AgenceEvenementielle.Models.Participant

@{
    ViewData["Title"] = "CreateParticipant";
}

<h1>CreateParticipant</h1>

<h4>Participant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateParticipant">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Delete.cshtml
@model AgenceEvenementielle.Models.Evenement

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evenement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lieu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lieu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horraire)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horraire)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Edit.cshtml
@model AgenceEvenementielle.Models.Evenement

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Evenement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lieu" class="control-label"></label>
                <input asp-for="Lieu" class="form-control" />
                <span asp-validation-for="Lieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horraire" class="control-label"></label>
                <input asp-for="Horraire" class="form-control" />
                <span asp-validation-for="Horraire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Index.cshtml
@model IEnumerable<AgenceEvenementielle.Models.Evenement>

@{
    ViewData["Title"] = "Evénements";
}


<h1 class="display-4; text-center">Bienvenue sur le gestionnaire des événements Wow Event </h1>

<h2>Evenements à venir </h2>

<table class="table">
     <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lieu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Horraire)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Participants)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lieu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Horraire)
            </td>
                <td>
                    <a asp-action="Participant">Liste des participants</a>
                </td>
            <td>
                    <button class="btn btn-outline-primary">
                        @Html.ActionLink("Modifier", "Edit", new { id = item.Nom }) 
                </button>
                <button class="btn btn-outline-primary">
                        @Html.ActionLink("Supprimer", "Delete", new { id = item.Nom })
                </button>
          

                
            </td>
        </tr>
}
    </tbody> 
</table>



    <a class="btn btn-outline-primary" asp-action="Create" role="button">Créer un événement</a>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Participant.cshtml
@model IEnumerable<AgenceEvenementielle.Models.Participant>

@{
    ViewData["Title"] = "Participant";
}

<h1>Participants</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AgenceEvenementielle/AgenceEvenementielle/Views/Evenement/Statistique.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Statistiques</h1>

AgenceEvenementielle/AgenceEvenementielle/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AgenceEvenementielle/AgenceEvenementielle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgenceEvenementielle</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenceEvenementielle.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgenceEvenementielle</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Evenement" asp-action="Statistique">Statistiques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Agence Evenementielle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>